<?php

/**
 * @file
 * Contains term_node.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function term_node_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the term_node module.
    case 'help.page.term_node':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow a term to be configured to show the content on a referenced node rather than the default term view') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function term_node_taxonomy_term_update(EntityInterface $entity) {
  // Invalidate the relevant cache entries.
  $tags[] = 'route_match';

  $resolver = \Drupal::service('term_node.resolver.term');
  // Clear the caches for the node that is now the term node.
  $nid = $resolver->getReferencedId($entity);
  $tags[] = 'node:' . $nid;

  // Clear the caches for the node that was previously the term node.
  if ($original = $entity->original) {
    $nid = $resolver->getReferencedId($original);
    $tags[] = 'node:' . $nid;
  }

  \Drupal::service('cache_tags.invalidator')->invalidateTags($tags);
}
